# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: vs2017-win2016

steps:
- powershell: |
    Write-Host "C free: $( (Get-PSDrive 'C').Free/1GB ) GB"
    Write-Host "D free: $( (Get-PSDrive 'D').Free/1GB ) GB"
  continueOnError: true
  displayName: Disk Space 1

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: ">=4.6.0"

- powershell: Write-Host "NuGetExeToolPath='$(NuGetExeToolPath)'"
  continueOnError: true
  displayName: NuGetExeToolPath after NuGet task

- task: NuGetAuthenticate@0
  continueOnError: true
  inputs:
    nuGetServiceConnections: OfficeNuGetFeed

- powershell: |
    Write-Host "C free: $( (Get-PSDrive 'C').Free/1GB ) GB"
    Write-Host "D free: $( (Get-PSDrive 'D').Free/1GB ) GB"
  continueOnError: true
  displayName: Disk Space 2

- task: CmdLine@2
  displayName: yarn install
  inputs:
    script: yarn install --frozen-lockfile

- powershell: |
    Write-Host "C free: $( (Get-PSDrive 'C').Free/1GB ) GB"
    Write-Host "D free: $( (Get-PSDrive 'D').Free/1GB ) GB"
  continueOnError: true
  displayName: Disk Space 3

- task: CmdLine@2
  displayName: yarn build
  inputs:
    script: yarn build

- powershell: |
    Write-Host "C free: $( (Get-PSDrive 'C').Free/1GB ) GB"
    Write-Host "D free: $( (Get-PSDrive 'D').Free/1GB ) GB"
  continueOnError: true
  displayName: Disk Space 4

- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    command: restore
    restoreSolution: vnext/ReactWindows-Desktop.sln
    feedsToUse: config
    nugetConfigPath: $(Build.SourcesDirectory)/vnext/NuGet.config
    restoreDirectory: packages/
    verbosityRestore: Detailed # Options: quiet, normal, detailed

- powershell: |
    Write-Host "C free: $( (Get-PSDrive 'C').Free/1GB ) GB"
    Write-Host "D free: $( (Get-PSDrive 'D').Free/1GB ) GB"
  continueOnError: true
  displayName: Disk Space 5

- task: PowerShell@2
  displayName: Build RNW via Office tools
  continueOnError: true
  inputs:
    targetType: filePath
    filePath: $(Build.SourcesDirectory)\vnext\Scripts\OfficeBuild.ps1
    arguments: build -ADOLog -NugetCmd $(NuGetExeToolPath) -MSBuildCmd 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe'

- powershell: |
    Write-Host "C free: $( (Get-PSDrive 'C').Free/1GB ) GB"
    Write-Host "D free: $( (Get-PSDrive 'D').Free/1GB ) GB"
  continueOnError: true
  displayName: Disk Space 6
