# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: vs2017-win2016

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- powershell: ls "env:"
  displayName: Print Environment

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: "=4.6.0"

- task: NuGetCommand@2
  displayName: Dummy NuGet tasktore
  continueOnError: true
  inputs:
    command: 'custom'

- powershell: Write-Host "NuGetExeToolPath='$(NuGetExeToolPath)'"
  continueOnError: true
  displayName: NuGetExeToolPath after NuGet task

- task: NuGetAuthenticate@0
  inputs:
   nuGetServiceConnections: AeulitzRNWexperiment

- task: PowerShell@2
  displayName: Build RNW via Office tools
  inputs:
    targetType: filePath
    filePath: $(Build.SourcesDirectory)\vnext\Scripts\OfficeBuild.ps1
    arguments: build -ADOLog -NugetExe $(NuGetExeToolPath) -APIKey z3teiygx364uapy4l3hf6lwwjrmzdvj5zuppcpiodyrjn6g3zljq

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
