# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: vs2017-win2016

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: ">=4.6.0"

- powershell: Write-Host "NuGetExeToolPath='$(NuGetExeToolPath)'"
  continueOnError: true
  displayName: NuGetExeToolPath after NuGet task

- task: NuGetAuthenticate@0
  continueOnError: true
  inputs:
    nuGetServiceConnections: OfficeNuGetFeed

- task: PowerShell@2
  displayName: Build RNW via Office tools
  inputs:
    targetType: filePath
    filePath: $(Build.SourcesDirectory)\vnext\Scripts\OfficeBuild.ps1
    arguments: build -ADOLog -NugetExe $(NuGetExeToolPath) -APIKey z3teiygx364uapy4l3hf6lwwjrmzdvj5zuppcpiodyrjn6g3zljq

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
